### ISSUE TITLE
where is the pdf tutorial for download?

### ISSUE THREAD

**Issue by joostshao** [sdiehl/kaleidoscope#18]
where is the pdf tutorial for download?

**Comment by joostshao** [comment]
i make the pdf perfectly, thank you !

**Comment by jaseemabid** [comment]
@sdiehl Can we provide a pdf for download? I'm facing issues generating the pdf with current latest version of pandoc.

**Comment by sdiehl** [comment]
@jaseemabid Here you go: [tutorial.pdf](https://github.com/sdiehl/kaleidoscope/files/1044765/tutorial.pdf)

**Comment by jaseemabid** [comment]
Thank you so much
