### ISSUE TITLE
Running cbits.c functions

### ISSUE THREAD

**Issue by esato** [sdiehl/kaleidoscope#20]
I am running the examples on a Mint Linux box.

When I try to run `extern putchard(x); putchard(120);` I get the following error message:

    LLVM ERROR: Program used external function 'putchard' which could not be resolved!

In order to build the chapter 4 example i did `make chapter4`.

Is there something I am missing?

**Comment by sdiehl** [comment]
Seems to be a weird edge case on Mint Linux.

Solution: http://stackoverflow.com/questions/29462859/haskell-llvm-general-jit-calling-a-c-function-on-the-fly-stephen-diehls-tutor/29527167#29527167
