### ISSUE TITLE
Idris does not use LLVM by default

### ISSUE THREAD

**Issue by hellerve** [sdiehl/kaleidoscope#21]
In the end of chapter 1 there is a list of languages using LLVM as backend. Idris in the list, but does not use LLVM by default, but [rather a backend that generates C code](https://github.com/idris-lang/Idris-dev/blob/master/src/IRTS/CodegenC.hs). There is, however, a [backend targetting LLVM](https://github.com/idris-hackers/idris-llvm), but the module seems to be unmaintained and [long broken](https://github.com/idris-hackers/idris-llvm/issues/3).

Cheers

**Comment by sdiehl** [comment]
It wasn't unmaintained at the time of writing, which was a few years ago.

**Comment by hellerve** [comment]
I will issue a pull request then, if you want me to. I also fixed a few typos and the like.

**Comment by sdiehl** [comment]
Removed Idris.
