### ISSUE TITLE
Compiling the preprocessor gives error about missing pandoc

### ISSUE THREAD

**Issue by Munksgaard** [sdiehl/kaleidoscope#28]
When running `stack ghc preprocessor.hs -- -o preprocessor` as described in the readme, I get the following error:

``` bash

preprocessor.hs:6:8:
    Could not find module ‘Text.Pandoc’
    Perhaps you meant
      Text.Parsec (from parsec-3.1.9@parse_8fSmqig53hOL2SEu1k9Tv0)
    Use -v to see a list of the files searched for.
```

I have pandoc installed, as well as libghc-pandoc-dev (`1.16.0.2~dfsg-1` on Ubuntu 16.04. Am I missing something else?

**Comment by Addisonbean** [comment]
Did you install pandoc using `stack install pandoc`? I had to install pandoc through stack in order for stack to find it.
