### ISSUE TITLE
Release on Hackage

### ISSUE THREAD

**Issue by amigalemming** [sdiehl/kaleidoscope#29]
How about releasing the tutorial package on Hackage? It would increase the visibility.

**Comment by sdiehl** [comment]
It causes problems because it needs to be linked against a system version of LLVM, which it outside of Hackage's domain.

**Comment by amigalemming** [comment]
On Sat, 6 Aug 2016, Stephen Diehl wrote:

> It causes problems because it needs to be linked against a system version of LLVM, which it outside of Hackage's domain.

I don't quite understand. There are many packages on Hackage that cannot 
be build on the Hackage server because of missing installed C libraries, 
including bindings to LLVM. Nonetheless these packages can be installed on 
user machines after the user installed the required C libraries.

**Comment by sdiehl** [comment]
Ok, I'll put it up I suppose.

**Comment by sdiehl** [comment]
Here you go: https://hackage.haskell.org/package/kaleidoscope
