### ISSUE TITLE
macOS Sierra/llvm 3.9 Support

### ISSUE THREAD

**Issue by Addisonbean** [sdiehl/kaleidoscope#35]
When running `stack build`, I get an error saying

        setup: The program 'llvm-config' version ==3.5.* is required but the version
        found at /usr/local/Cellar/llvm/3.9.1/bin/llvm-config is version 3.9.1

I am using macOS Sierra, which doesn't support llvm 3.5. Is there anyway to get this to work with a newer version of llvm like 3.9?

**Comment by doersino** [comment]
Install LLVM 4.0 (see [here](https://github.com/llvm-hs/llvm-hs/blob/llvm-4/README.md#homebrew)) and try again now.

**Comment by Addisonbean** [comment]
It works perfectly now, thanks so much!
