### ISSUE TITLE
`stack ghc preprocessor.hs -- -o preprocessor` fails

### ISSUE THREAD

**Issue by Addisonbean** [sdiehl/kaleidoscope#36]
I am trying to build kaleidoscope on Ubuntu 15.10.

I installed llvm-3.5 and libedit-dev, and`stack build` runs successfully. Then when I run `stack ghc preprocessor.hs -- -o preprocessor`, I get this error:

```
[1 of 1] Compiling Main             ( preprocessor.hs, preprocessor.o )

preprocessor.hs:46:35:
    Couldn't match type ‘Either Text.Pandoc.Error.PandocError Pandoc’
                   with ‘Pandoc’
    Expected type: Either Text.Pandoc.Error.PandocError Pandoc
                   -> String
      Actual type: Pandoc -> String
    In the second argument of ‘(.)’, namely ‘writeMarkdown def’
    In the second argument of ‘(>>=)’, namely
      ‘putStrLn . writeMarkdown def’
```

Any ideas what could be going on here?

**Comment by sdiehl** [comment]
I think there's an incompatible version of pandoc being used. The preprocessor was originally written for `1.12`.

**Comment by sdiehl** [comment]
You may need to `stack install pandoc`  manually using a resolver that matches that version.
